bool espSend(String comando, int tiempo);
bool espCheck(void);
bool disableEcho(void);
bool disconnectWifi(void);
bool espConnect(String red, String clave);
bool espGetIP(void);
bool espServer(void);
bool iniWifi(void);
void checkEnvioWiFi(void);
void configWiFiParams(void);
void transmTempWifi(void);